default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: lockwood
  password: qwe123qwe
  host: db
  database: db1
  socket: /var/run/mysqld/mysqld.sock   

development:
  <<: *default
  database: db1

test:
  <<: *default
  database: db1_test

production:
  <<: *default
  database: db1_production
  username: lockwood
  password: qwe123qwe
