default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  socket: /var/run/mysqld/mysqld.sock


development:
  <<: *default
  database: db1

test:
  <<: *default
  database: db1_test

production:
  <<: *default
  database: db1_production
  username: lockwood
  password: qwe123qwe
